### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-test-utils#17]
When using prisma-test-utils via prisma-test-utils-automation, some databases (schemas from: https://github.com/prisma/database-schema-examples) fail with this error message:

```
Error in: concrete5
RangeError: Maximum call stack size exceeded
    at isOrderWellDefinedInPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:801:38)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:771:15)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

```
Error in: magento
RangeError: Maximum call stack size exceeded
    at Function.values (<anonymous>)
    at isOrderWellDefinedInPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:802:21)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:771:15)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

```
Error in: mapos
RangeError: Maximum call stack size exceeded
    at Function.values (<anonymous>)
    at isOrderWellDefinedInPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:802:21)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:771:15)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

```
Error in: northwind
RangeError: Maximum call stack size exceeded
    at Array Iterator.next (<anonymous>)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:768:18)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

```
Error in: okky
RangeError: Maximum call stack size exceeded
    at Function.values (<anonymous>)
    at isOrderWellDefinedInPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:802:21)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:771:15)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

```
Error in: orangehrm
RangeError: Maximum call stack size exceeded
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

```
Error in: xpressengine
RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (<anonymous>)
    at C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:804:16
    at Array.every (<anonymous>)
    at isOrderWellDefinedInPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:802:45)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:771:15)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

**Comment by janpio** [comment]
PostgreSQL:

```
Error in: canvas-lms
RangeError: Maximum call stack size exceeded
    at Function.values (<anonymous>)
    at isOrderWellDefinedInPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:802:21)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:771:15)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
    at sort (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:788:20)
```

**Comment by janpio** [comment]
### Theory
Many tables lead to much sorting

### Data

mysql:
- concrete5: 330
- magento: 390
- mapos: 24
- northwind: 20
- okky: 39
- orangehrm: 146
- xpressengine: 79

postgres:
- canvas-lms: 234
- mastodon: 70

### Conclusion
Not really that many tables. Possibly many FK relations? Difficult to figure out.

**Comment by maticzav** [comment]
@janpio this should be fixed in the latest commit.
