### ISSUE TITLE
ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Fields(["PlaylistId"]) } })

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-test-utils#18]
When using `prisma-test-utils` via `prisma-test-utils-automation`, some databases fail with this error message:

```
Error in: chinook
PrismaClientUnknownRequestError:
Invalid `seed = await client[methodName].create()` invocation in
C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:973:45

   969
   970 /**
   971  * Load the data to database.
   972  */
→  973 const seed = await client[methodName].create(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Fields(["PlaylistId"]) } })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\chinook\node_modules\prisma-client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Schemas from: https://github.com/prisma/database-schema-examples

Not sure this is a `prisma-test-utils` or a Prisma Client or Engine error.

**Comment by janpio** [comment]
This chinook has a compound primary key in the table `PlaylistTrack` over the fields `PlaylistId` and `TrackId`. `test-utils` might not be taking this into consideration somehow and trying to create an entry that crashes because of that.

**Comment by maticzav** [comment]
@janpio is there a property in the DMMF that I can use to determine whether a model is an index? Currently, `PlaylistTrack` acts as if it had two ID fields. DB, however, expects connect-identifiers.

```prisma
model PlaylistTrack {
  PlaylistId Int @default(0)
  TrackId    Int @default(0)

  @@id([PlaylistId, TrackId])
  @@index([TrackId], name: "IFK_PlaylistTrackTrackId")
}
```

**Comment by janpio** [comment]
I do not understand what you are asking. `PlaylistTrack` has a compound identifier that spans both its fields/columns.

**Comment by maticzav** [comment]
I don't understand what you mean, but it seems like `PlaylistId` and `PlaylistTrack` refer to actual ids of existing `Playlist` and `Track`. Usually, these would come in like relations. Here, however, they are just regular `Int` fields.

Am I missing something?

**Comment by janpio** [comment]
What you posted is 1 table that has a primary key with 2 columns, and an index on one of these columns - nothing else really.

Looking at the underlying SQL there should also be two FKs represented somehow:
```sql
ALTER TABLE `PlaylistTrack` ADD CONSTRAINT `FK_PlaylistTrackPlaylistId`
    FOREIGN KEY (`PlaylistId`) REFERENCES `Playlist` (`PlaylistId`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `PlaylistTrack` ADD CONSTRAINT `FK_PlaylistTrackTrackId`
    FOREIGN KEY (`TrackId`) REFERENCES `Track` (`TrackId`) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX `IFK_PlaylistTrackTrackId` ON `PlaylistTrack` (`TrackId`);
```
https://github.com/prisma/database-schema-examples/blob/cdba7b880b5d9cba9ec5c97c83aa083ea85d89c3/mysql/chinook/schema.sql#L172-L178

This lead me to check the Introspection result of that table. This is what it really looks like:

```
model PlaylistTrack {
  PlaylistId Playlist
  TrackId    Track

  @@id([PlaylistId, TrackId])
  @@index([TrackId], name: "IFK_PlaylistTrackTrackId")
}
```

What version created this Prisma Schema for you?

**Comment by maticzav** [comment]
That indeed looks better. I am using `preview23`.

**Comment by janpio** [comment]
Hm, in the past we had similar problem when the import of the `schema.sql` was broken locally. Often the foreign keys are defined at the end of the `.sql`, which means you could have all the tables and primary keys, but not the foreign keys which could explain the model you posted.

**Comment by divyenduz** [comment]
---

Internal notes: 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/mysql_public_test_utils_xpressengine_stderr.log

**Comment by janpio** [comment]
Seems to me that test-utils tries to leave of the optional `site_srl` in the Client call, but MySQL does not like that at all and fails. Strange.
