### ISSUE TITLE
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1292, message: "Incorrect datetime value: \'2081-07-13 01:02:18\' for column \'last_update\' at row 1", state: "22007" })) })

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-test-utils#20]
When using prisma-test-utils via prisma-test-utils-automation, some databases (schemas from: https://github.com/prisma/database-schema-examples) fail with this error message:

```
Error in: sakila
PrismaClientUnknownRequestError:
Invalid `: new actorClient()` invocation in
C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\sakila\node_modules\prisma-client\index.js:648:7

   644   args || {},
   645   [],
   646   errorFormat,
   647   measurePerformance
→  648 ) : new actorClient

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1292, message: "Incorrect datetime value: \'2081-07-13 01:02:18\' for column \'last_update\' at row 1", state: "22007" })) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\sakila\node_modules\prisma-client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

SQL behind this field:

```
CREATE TABLE actor (
    actor_id integer DEFAULT nextval('actor_actor_id_seq'::regclass) NOT NULL,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    last_update timestamp without time zone DEFAULT now() NOT NULL
);
```

**Comment by maticzav** [comment]
We are now leveraging `prisma-client-js` to do date manipulation. Input value is of type (node) Date.

**Comment by janpio** [comment]
Meaning what exactly in context of this issue?

**Comment by maticzav** [comment]
not sure 😅

you can ignore it. I thought this was addressing `test-utils`
