### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-test-utils#24]
When using prisma-test-utils via prisma-test-utils-automation, some databases (schemas from: https://github.com/prisma/database-schema-examples) fail with this error message:

```
Error in: basic-blog (postgres)
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:1579:29
    at Array.reduce (<anonymous>)
    at insertFixtureIntoPool (C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:1578:10)
    at C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:995:31
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jan\Documents\prisma-test-utils\dist\static\seed.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by maticzav** [comment]
@janpio could you send me the `export DEBUG=“*”`?

**Comment by maticzav** [comment]
This seems to be the bug inside the `Dataloader` - `.create` method returns `undefined`.

This seems to be a regression in the new version of Prisma Client since my local setup also fails now.

Relevant part: https://github.com/prisma/prisma-client-js/blob/ff92b6a5bf1c5f8196900bccff01a97b070e1783/packages/photon/src/runtime/Dataloader.ts#L35

**Comment by maticzav** [comment]
#29

**Comment by janpio** [comment]
How is https://github.com/prisma/prisma-test-utils/issues/29 connected here?

**Comment by janpio** [comment]
> This seems to be the bug inside the `Dataloader` - `.create` method returns `undefined`.
> 
> This seems to be a regression in the new version of Prisma Client since my local setup also fails now.
> 
> Relevant part: [prisma/prisma-client-js:packages/photon/src/runtime/Dataloader.ts@`ff92b6a`#L35](https://github.com/prisma/prisma-client-js/blob/ff92b6a5bf1c5f8196900bccff01a97b070e1783/packages/photon/src/runtime/Dataloader.ts#L35)

Did you create an issue and reproduction for this?

**Comment by maticzav** [comment]
Divy’s issue is causing this bug. Once that gets resolved this bug shouldn’t appear anymore.
