### ISSUE TITLE
PANIC: column on null constraint violation error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-test-utils#25]
When using prisma-test-utils via prisma-test-utils-automation, some databases (schemas from: https://github.com/prisma/database-schema-examples) fail with this error message:

```
Error in: chinook (postgres)
PrismaClientUnknownRequestError:
Invalid `seed = await client[methodName].create()` invocation in
C:\Users\Jan\Documents\prisma-test-utils\src\static\seed.ts:973:45

   969
   970 /**
   971  * Load the data to database.
   972  */
→  973 const seed = await client[methodName].create(

PANIC: column on null constraint violation error
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-test-utils-automation\dbs\chinook\node_modules\prisma-client\index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by divyenduz** [comment]
I don't know how you ran into this with Chinook. I could only observe this for the database mentioned below.

I am not fully sure what this is about yet, maybe inserting a record with the respective foreign key record not inserted yet.  

---

Internal notes: 

Test utils database(s) affected: 
- https://github.com/prisma/introspection-engine-output/blob/test_utils/test-utils/results/postgresql_public_test_utils_cms-utilization-db_stderr.log

**Comment by janpio** [comment]
The SQL shows that the table `providers_individuals` has a PK that is also a FK to the table `providers`. That is currently not supported in Prisma, so test-utils does not have any way to find out about that it should insert an existing providers.id here.
